/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bengkel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Login_m;

/**
 *
 * @author Sigit
 */
public class history extends javax.swing.JInternalFrame {
        private Connection conn = new Koneksi().connect();
        private DefaultTableModel tabmode;
            java.util.Date tglsekarang = new java.util.Date();
          private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
        private final String tanggal = smpdtfmt.format(tglsekarang);
    /**
     * Creates new form history
     */
    public history() {
                 ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        initComponents();
        datatable();
    }
    
    private void datatable() {
        String id_login = Login_m.getId_login();
        Object[] Baris = {"Tanggal","No Faktur", "Nama Pelanggan", "No Polisi", "Keluhan", "Nama Mekanik","Total"};
        tabmode = new DefaultTableModel(null, Baris);
        tbl_history.setModel(tabmode);
        String sql = "select DATE_FORMAT(a.tanggal,'%d/%m/%Y') as tanggal,a.no_faktur,c.nm_pelanggan,d.nm_pelanggan"
                + "a.no_polisi,a.keluhan,a.total "
                + "from service_motor a "
                + "join login b on a.kasir = b.id_login "
                + "join pelanggan c on a.kd_pelanggan = c.id_pelanggan "
                + "join mekanik d on a.kd_mekanik = d.id_mekanik"
                + "where a.kasir = '"+id_login+"' AND DATE_FORMAT(a.tanggal,'%d/%m/%Y') = '"+tanggal+"' "
                + "order by a.no_faktur DESC";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String tanggal1 = hasil.getString("tanggal");
                String no_faktur = hasil.getString("no_faktur");
                String nama_pelanggan = hasil.getString("nm_pelanggan");
                String nama_mekanik = hasil.getString("nm_mekanik");
                String no_polisi = hasil.getString("no_polisi");
                String keluhan = hasil.getString("keluhan");
                String total = hasil.getString("total");
                String[] data = {tanggal1,no_faktur,nama_pelanggan,nama_mekanik,no_polisi,keluhan,total};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bntRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_history = new javax.swing.JTable();
        txCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setTitle("History Transaksi");

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("History Service");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bntRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/013-refresh.png"))); // NOI18N
        bntRefresh.setText("Refresh");

        tbl_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_historyMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_history);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntRefresh))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bntRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001-search.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txCari)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txCari))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String btn_cari = btnCari.getText();
        String cari = txCari.getText();
        
        if(cari.equals("")) {
           JOptionPane.showMessageDialog(null, "Kolom Pencarian Tidak Boleh Kosong"); 
        }else{
          if (btn_cari.equals("Cari")){
              String id_login = Login_m.getId_login();
        Object[] Baris = {"Tanggal","No Faktur", "Nama Pelanggan", "No Polisi", "Keluhan", "Nama Mekanik","Total"};
        tabmode = new DefaultTableModel(null, Baris);
        tbl_history.setModel(tabmode);
        String sql = "select DATE_FORMAT(a.tanggal,'%d/%m/%Y') as tanggal,a.no_faktur,c.nm_pelanggan,d.nm_pelanggan"
                + "a.no_polisi,a.keluhan,a.total "
                + "from service_motor a "
                + "join login b on a.kasir = b.id_login "
                + "join pelanggan c on a.kd_pelanggan = c.id_pelanggan "
                + "join mekanik d on a.kd_mekanik = d.id_mekanik"
                + "where a.kasir = '"+id_login+"' AND DATE_FORMAT(a.tanggal,'%d/%m/%Y') = '"+tanggal+"' "
                + " AND (a.no_faktur like '%" +cari+ "%' OR c.nm_pelanggan like '%" +cari+ "%' OR d.nm_mekanik like '%" +cari+ "%')  "
                + "order by a.no_faktur DESC";
        
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) {
                String tanggal1 = hasil.getString("tanggal");
                String no_faktur = hasil.getString("no_faktur");
                String nama_pelanggan = hasil.getString("nm_pelanggan");
                String nama_mekanik = hasil.getString("nm_mekanik");
                String no_polisi = hasil.getString("no_polisi");
                String keluhan = hasil.getString("keluhan");
                String total = hasil.getString("total");
                String[] data = {tanggal1,no_faktur,nama_pelanggan,nama_mekanik,no_polisi,keluhan,total};
                tabmode.addRow(data);
                btnCari.setText("Batal");
            }else{
                JOptionPane.showMessageDialog(null, "Data Tidak Di Temukan"); 
                 datatable();
            btnCari.setText("Cari");
            }
        } catch (Exception e) {
            datatable();
            btnCari.setText("Cari");
        }
          }else{
              btnCari.setText("Cari");
              datatable();

          }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tbl_historyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_historyMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_historyMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRefresh;
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_history;
    private javax.swing.JTextField txCari;
    // End of variables declaration//GEN-END:variables
}
