/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bengkel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sigit
 */
public class Report_sparepart extends javax.swing.JInternalFrame {
private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
        private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());

    /**
     * Creates new form Report_pelanggan
     */
    public Report_sparepart() {
                    ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        initComponents();
                    datatable();
    }
    
    private void datatable() {
    Date dttfrom = dtfrom.getDate();
    Date dttthru = dtthru.getDate();
    String tanggal1 = smpdtfmt.format(dttfrom);
    String tanggal2 = smpdtfmt.format(dttthru);
        Object[] Baris = {"ID SPAREPART","Kode Sparepart", "Nama Sparepart", "Stok Awal","Stok Masuk","Stok Keluar","Stok Akhir"};
        tabmode = new DefaultTableModel(null, Baris);
        tbl_pelanggan1.setModel(tabmode);
        tbl_pelanggan1.getColumnModel().getColumn(0).setWidth(0);        
        tbl_pelanggan1.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_pelanggan1.getColumnModel().getColumn(0).setMaxWidth(0);
        String sql = "SELECT a.id_sparepart, a.kd_sparepart, a.nm_sparepart" +
" (select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') < '"+dttfrom +"' AND jenis = 'IN') - (select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') < '"+dttfrom+"' AND jenis = 'OUT') as stok_awal, " +
" (select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') between  '"+dttfrom+"' AND '"+dttthru+"' AND jenis = 'IN') AS stok_masuk, " +
" (select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') between  '"+dttfrom+"' AND '"+dttthru+"' AND jenis = 'OUT') as stok_keluar, " +
" ((select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') < '"+dttfrom+"' AND jenis = 'IN') - (select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') < '"+dttfrom+"' AND jenis = 'OUT')) + " + 
"(select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') between  '"+dttfrom+"' AND '"+dttthru+"' AND jenis = 'IN') - (select IFNULL(sum(qty),0) from stok where id_sparepart = a.id_sparepart AND DATE_FORMAT(tanggal,'%Y-%m-%d') between  '"+dttfrom+"' AND '"+dttthru+"' AND jenis = 'OUT') as stok_akhir" +
" from sparepart a " +
" left join stok b on a.id_sparepart = b.id_sparepart " +
" where a.id_sparepart IN (SELECT id_sparepart from stok where DATE_FORMAT(tanggal,'%Y-%m-%d') between '"+dttfrom+"' AND '"+dttthru+"' AND jenis IN ( 'IN','OUT'))" +
" GROUP by a.kd_sparepart" +
" ORDER BY a.kd_sparepart";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String id = hasil.getString("id_sparepart");
                String kode = hasil.getString("kd_sparepart");
                String nama = hasil.getString("nm_sparepart");
                String stok_awal = hasil.getString("stok_awal");
                String stok_masuk = hasil.getString("stok_masuk");
                String stok_keluar = hasil.getString("stok_keluar");
                String stok_akhir = hasil.getString("stok_akhir");

                String[] data = {id,kode,nama,stok_awal,stok_masuk,stok_keluar,stok_akhir};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pelanggan1 = new javax.swing.JTable();
        dtfrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtthru = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT SPAREPART & STOK");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006-printer.png"))); // NOI18N
        btn_print.setText("PRINT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        tbl_pelanggan1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_pelanggan1);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERIODE");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S / D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(dtthru, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_print)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_print)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(1, 1, 1))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dtfrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtthru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_btn_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_print;
    private com.toedter.calendar.JDateChooser dtfrom;
    private com.toedter.calendar.JDateChooser dtthru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pelanggan1;
    // End of variables declaration//GEN-END:variables
}
